services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/pallocdb
  db:
    image: mongo:8
    ports:
      - 27017:27017
    volumes:
      - database:/data/db

volumes:
  database: